---
jdk_packages:
  - java-1.8.0-openjdk
  - java-1.8.0-openjdk-devel
  - libselinux-python

java_deploy_options: []
jre_lib_path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-1.b14.el6.x86_64/jre/lib
java_home_path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-1.b14.el6.x86_64/jre
