# main.yml - Nginx installation
---
- name: Install Nginx
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx_version_specific

- name: Ensure Nginx is started and enabled at boot time.
  service:
    name: nginx
    state: started
    enabled: yes
  failed_when: False

- name: Open port 80 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 80 -j ACCEPT"
  when: iptables_config

- name: Open port 443 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 443 -j ACCEPT"
  when: iptables_config

- name: Save rules
  command: "/sbin/service iptables save"
  when: iptables_config

